name: Build App

on: 
  push:
    branches:
      - "master"
    paths:
      - "client/**"
      - "server/**"

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Build Server
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pyinstaller --clean -y webserver.spec
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Server
          path: server/dist

  client:
    runs-on: ubuntu-latest
    needs: server
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Server
          path: client/src/dist
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install && yarn make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Client
          path: client/out/ProxVoice-linux-x64