name: Build Client

defaults:
  run:
    working-directory: client

on:
  push:
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            client/target
          key: ${{ runner.os }}-cargo-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path client/Cargo.toml --release
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          REQUEST_SECRET: ${{ secrets.REQUEST_SECRET }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: client-${{ runner.os }}
          path: |
            client/target/release/proxvoice
            client/target/release/proxvoice.exe