name: Build Mod

defaults:
  run:
    working-directory: mod

on:
  push:
    paths:
      - "mod/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build Jar
        run: ./gradlew jar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Mod
          path: mod/build/libs/*.jar